## 00. Pytorch Fundamentals

In [61]:
print("yo, let's learn pytorch. Gonna be great")

yo, let's learn pytorch. Gonna be great


In [62]:
!nvidia-smi

Mon Jan 22 09:21:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [63]:
## importing libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors
### Creating tensors

In [64]:
# scalar tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [65]:
# to check the dimensions
# since it's a scalar hence no dimensions
scalar.ndim

0

In [66]:
# to get tensor back as python int
scalar.item()

7

In [67]:
#vector - mathematically vector has some magnitude and direction

vector = torch.tensor([6,6])
vector


tensor([6, 6])

In [68]:
vector.ndim

1

In [69]:
#ndim just give the count of pair of square brackets
#shape kinda gives the number of elements

vector.shape

torch.Size([2])

In [70]:
#Matrix

matrix = torch.tensor([[7,7],
                       [6,6]])

matrix

tensor([[7, 7],
        [6, 6]])

In [71]:
matrix.ndim

2

In [72]:
matrix.shape

torch.Size([2, 2])

In [73]:
# Tensor

tensor = torch.tensor([[[1,1,1],
                        [2,2,2],
                        [3,3,3]]])

tensor

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [74]:
tensor.ndim

3

In [75]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

Randome tensors are important because the way neural networks is that it starts with tensors full of random numbers and
then adjust those random numbers to better represent the data

`start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers`

In [76]:
# creating a random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4330, 0.7329, 0.7029, 0.5346],
        [0.5402, 0.8578, 0.0015, 0.8251],
        [0.7775, 0.6012, 0.3734, 0.5574]])

In [77]:
random_tensor.ndim


2

In [78]:
random_tensor.shape

torch.Size([3, 4])

In [79]:
#creating a random tensor with similar shape to image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # size = height,weight,color channels


In [80]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeroes and Ones tensors

They are usually helpful in creating masks.
Masking is a method of indicating which elements of a matrix or vector should and should not be used in the form of (0s and 1s)

In [81]:
#creating tensors of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [82]:
#creating tensor of all ones

ones = torch.ones(size=(4,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [83]:
#unless we specify the data type, the default is float32
zeros.dtype,ones.dtype

(torch.float32, torch.float32)

### Creating range of tensors or tensors like

In [84]:
#using torch.arange(start,end,step), start is included and end is not, step is one default
zero_to_one = torch.arange(0,1000,77 )
zero_to_one

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [85]:
#creating tensors like, so that we can replicate the shape of other tensor without explicitly defining the shape
zeros_like_above = torch.zeros_like(zero_to_one)
zeros_like_above

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Datatype in tensors

Note: Datatypes in tensors are cause broadly these 3 errors in pytorch or deeplearning
  1. Tensors not in right datatype
  2. Tensors not in right shape
  3. Tensors not in right device

In [86]:
float_32_tensor = torch.tensor([3.0,6.9,7.8],
                               dtype = None, # datatype of tensor it can be float32,float16 and many more
                               device = None, #cpu or cuda for selecting either cpu or gpu
                               requires_grad = False, # to keep the gradients while computing this tensors
                               )
float_32_tensor

tensor([3.0000, 6.9000, 7.8000])

In [87]:
float_32_tensor.dtype

torch.float32

In [88]:
#convertig float32 tensor into float16 tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.0000, 6.8984, 7.8008], dtype=torch.float16)

In [89]:
float_16_tensor.dtype

torch.float16

 ### Getting information from tensors
  1. Tensors not in right datatype -- to check datatype `tensor.dtype`
  2. Tensors not in right shape --  to check shape `tensor.shape`
  3. Tensors not in right device -- to check device `tensor.device`

In [90]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8337, 0.0823, 0.8457, 0.5307],
        [0.7138, 0.6253, 0.0432, 0.0647],
        [0.9506, 0.9827, 0.9751, 0.7982]])

In [91]:
some_tensor.dtype

torch.float32

In [92]:
some_tensor.shape

torch.Size([3, 4])

In [93]:
some_tensor.device

device(type='cpu')

### Manipulating tensors (tensor operations)
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [94]:
# creating a tensor

tensor = torch.tensor([1,2,3])

# addition
print(tensor+10)
#subtraction
print(tensor-87)
#mulitplication
print(tensor*9)
#division
print(tensor/3)

tensor([11, 12, 13])
tensor([-86, -85, -84])
tensor([ 9, 18, 27])
tensor([0.3333, 0.6667, 1.0000])


In [95]:
# there are builtin functions of pytorch for this too but it's kinda easier to use the python way
# addition
print(torch.add(tensor,10))
#subtraction
print(torch.sub(tensor,10))
#mulitplication
print(torch.mul(tensor,9))
#division
print(torch.div(tensor,3))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([ 9, 18, 27])
tensor([0.3333, 0.6667, 1.0000])


### Matrix Multiplication
There are basically two ways for matrix mulitplication in nueral networks or deep learning
* element wise
* matrix multiplication (dot product)

Two rules that need to satisfy to make matrix multiplication works:
* the inner dimension should match
* the output matrix have the outer dimension

In [98]:
# element wise multuiplication
print(tensor ,'*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [100]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

### Most common issue in matrix multiplication is the shape issue

In [102]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

#torch.mm(tensor_A,tensor_B) torch.mm is same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix this shape issue we can manipulate the shape of one of our tensors using **Transpose** menthod
**Transpose** basically switches the axes or the dimension of the given tensor

In [103]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [105]:
tensor_B.T.shape ## .T gives the transpose of the tensor

torch.Size([2, 3])

In [108]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the max,min,mean,sum,etc (Tensor aggregation)

In [109]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [111]:
#minimum
print(f"minimum {torch.min(x), x.min()}")
#maximum
print(f"maximum {torch.max(x), x.max()}")
#mean here mean function require specific type of input
print(f"mean {torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()}")
#sum
print(f"sum {torch.sum(x), x.sum()}")

minimum (tensor(0), tensor(0))
maximum (tensor(90), tensor(90))
mean (tensor(45.), tensor(45.))
sum (tensor(450), tensor(450))


### Finding the positional minimum and maximum

In [112]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [114]:
#argmin
print(f"position (index) of minimum value in the tensor {x.argmin()}")
#argmax
print(f"position (index)  of maximum value in the tensor {x.argmax()}")

position (index) of minimum value in the tensor 0
position (index)  of maximum value in the tensor 9


### Reshaping, Stacking, Squeezing and Unsqueezing (tensors)